apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      volumes:
        - name: tasks-volume
          emptyDir: {}

      initContainers:
        - name: wait-for-service
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nslookup myservice.default.svc.cluster.local; do echo waiting for myservice; sleep 2; done",
            ]

        - name: perform-task
          image: busybox
          command:
            [
              "sh",
              "-c",
              'echo "Init container tasks completed" > /tasks/status.txt',
            ]
          volumeMounts:
            - name: tasks-volume
              mountPath: /tasks

      containers:
        - name: main-container
          image: busybox
          command:
            [
              "sh",
              "-c",
              "while true; do echo 'main container running'; sleep 10; done",
            ]
          volumeMounts:
            - name: tasks-volume
              mountPath: /tasks
