apiVersion: v1
kind: Service
metadata:
  name: myservice
  labels:
    env: prod
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    env: prod
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: adapter-container-deployment
  labels:
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      env: prod
  template:
    metadata:
      labels:
        env: prod
    spec:
      initContainers:
        - name: wait-for-service
          image: busybox
          command:
            - "sh"
            - "-c"
            - "until nslookup myservice.default.svc.cluster.local; do echo waiting for myservice; sleep 2; done"
        - name: perform-task
          image: busybox
          command:
            - "sh"
            - "-c"
            - 'echo "Init container tasks completed" > /tasks/status.txt'
          volumeMounts:
            - name: shared-vol
              mountPath: /tasks

      containers:
        - name: adapter-container
          image: kiran2361993/kubegame:v1
          command:
            - "sh"
            - "-c"
            - "while true; do echo '<h1>'$(date)'</h1>' >> /html/index.html; sleep 5; done"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: shared-vol
              mountPath: /html/

        - name: main-container
          image: kiran2361993/kubegame:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: shared-vol
              mountPath: /usr/share/nginx/html/

      volumes:
        - name: shared-vol
          emptyDir: {}
