apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMrRENDQWVDZ0F3SUJBZ0lNR0RITjVQSGY3WVdKaUtmZU1BMEdDU3FHU0liM0RRRUJDd1VBTUJneEZqQVUKQmdOVkJBTVREV3QxWW1WeWJtVjBaWE10WTJFd0hoY05NalV3TXpJNU1EWXdNVFUwV2hjTk16VXdNekk1TURZdwpNVFUwV2pBWU1SWXdGQVlEVlFRREV3MXJkV0psY201bGRHVnpMV05oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGCkFBT0NBUThBTUlJQkNnS0NBUUVBMkg3a2N2VWFGQmV4Wkk1SGhIS0RMMHZVZkJUWlQxVFZRbll1ajZkcmp3d2QKT05qZHdwZ25mZlQ5L0IycmNDSDZ4VjN5azQ3am1LQVZhRkpMS081L2pVK2Y4R3hCS285d2NUSjF2Sk9hZDd0SAptUFBHU1R0UCtCa2xreG9iT3hHdmVVK1FBUGdlT0ZzM1lqa2NYNEdhOHZzUU15TEN0WGJhZ3QyV3RJdTdzVHpGCng2N3pqczZKdVFFQk9iZ3FEdHJTY29BTjIyS00ySVMxOUI3UGZOL0IrclVWT1RvUzl5L2pTaERLWDduWGZwTjEKb2pubXNNUTdrMzdyYjNlbzQ2Y2g5c0JGL2svUzFQMjJmc3c1VXVWWlJPM05rQTlWMkJUaXMwci8za3ZycFUxNAo2SkN1enBqK2lMNEg3cGZyQTczNmc4WHFaM21HK2ZpRmh4MTNRVE1aK3dJREFRQUJvMEl3UURBT0JnTlZIUThCCkFmOEVCQU1DQVFZd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVW1TN2JXeW4zR3lNcHoxclkKNWpTejkrOTVnT293RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUxZdnZCMGdqMWc2N2tYR0Y2MCtqTWZadytsTgpYMGUrN0h2MzZlUTZFLyttQnozTEZ6U0hwZDJBVXlrUUc1T0c2ZTBQcWQ4YTFhc3hmVHRmUDY1Q2ZMbGhHaTlTCnNTdGJPc1BWWDFKRnU2Q3NvUUJpRUFldnY4cjNhRkp2T2dJVXlKd1R4L2t4eUZNdkZkeHQrbzRLWkFZMWtHSGwKVFhURlRhY0Z5bzRDSnQ2L0N5ODNKZnVOQTdjVDhwdWRtblcwak0yeEd2RHZHcXN0ekFTdXc0Nzl5VDVzaGlHYQpTTFczdUJKWDBQL3lDTWttaTg5OWRsQkhxTTVqaWdXdlNvdlF1ZE0yenR5cENrcDZWUTYxNzhrd0xOeWQwSDF0CmRzVjFRZ3R5UFdJMDJKOXNrYjAwWFRFLzNYUkVPL1Z2RXk5ZlJEL3RHYlIrSjBTNXFtTUFUeTIzR1dZPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      server: https://api.gokulexi.shop
      tls-server-name: api.internal.gokulexi.shop
    name: gokulexi.shop
contexts:
  - context:
      cluster: gokulexi.shop
      namespace: development
      user: user1
    name: user1-context
current-context: user1-context
kind: Config
users:
  - name: user1
    user:
    client-certificate: /root/user1.crt
    client-key: /root/user1.key


----

apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMrRENDQWVDZ0F3SUJBZ0lNR0RITjVQSGY3WVdKaUtmZU1BMEdDU3FHU0liM0RRRUJDd1VBTUJneEZqQVUKQmdOVkJBTVREV3QxWW1WeWJtVjBaWE10WTJFd0hoY05NalV3TXpJNU1EWXdNVFUwV2hjTk16VXdNekk1TURZdwpNVFUwV2pBWU1SWXdGQVlEVlFRREV3MXJkV0psY201bGRHVnpMV05oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGCkFBT0NBUThBTUlJQkNnS0NBUUVBMkg3a2N2VWFGQmV4Wkk1SGhIS0RMMHZVZkJUWlQxVFZRbll1ajZkcmp3d2QKT05qZHdwZ25mZlQ5L0IycmNDSDZ4VjN5azQ3am1LQVZhRkpMS081L2pVK2Y4R3hCS285d2NUSjF2Sk9hZDd0SAptUFBHU1R0UCtCa2xreG9iT3hHdmVVK1FBUGdlT0ZzM1lqa2NYNEdhOHZzUU15TEN0WGJhZ3QyV3RJdTdzVHpGCng2N3pqczZKdVFFQk9iZ3FEdHJTY29BTjIyS00ySVMxOUI3UGZOL0IrclVWT1RvUzl5L2pTaERLWDduWGZwTjEKb2pubXNNUTdrMzdyYjNlbzQ2Y2g5c0JGL2svUzFQMjJmc3c1VXVWWlJPM05rQTlWMkJUaXMwci8za3ZycFUxNAo2SkN1enBqK2lMNEg3cGZyQTczNmc4WHFaM21HK2ZpRmh4MTNRVE1aK3dJREFRQUJvMEl3UURBT0JnTlZIUThCCkFmOEVCQU1DQVFZd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVW1TN2JXeW4zR3lNcHoxclkKNWpTejkrOTVnT293RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUxZdnZCMGdqMWc2N2tYR0Y2MCtqTWZadytsTgpYMGUrN0h2MzZlUTZFLyttQnozTEZ6U0hwZDJBVXlrUUc1T0c2ZTBQcWQ4YTFhc3hmVHRmUDY1Q2ZMbGhHaTlTCnNTdGJPc1BWWDFKRnU2Q3NvUUJpRUFldnY4cjNhRkp2T2dJVXlKd1R4L2t4eUZNdkZkeHQrbzRLWkFZMWtHSGwKVFhURlRhY0Z5bzRDSnQ2L0N5ODNKZnVOQTdjVDhwdWRtblcwak0yeEd2RHZHcXN0ekFTdXc0Nzl5VDVzaGlHYQpTTFczdUJKWDBQL3lDTWttaTg5OWRsQkhxTTVqaWdXdlNvdlF1ZE0yenR5cENrcDZWUTYxNzhrd0xOeWQwSDF0CmRzVjFRZ3R5UFdJMDJKOXNrYjAwWFRFLzNYUkVPL1Z2RXk5ZlJEL3RHYlIrSjBTNXFtTUFUeTIzR1dZPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      server: https://api.gokulexi.shop
      tls-server-name: api.internal.gokulexi.shop
    name: gokulexi.shop
contexts:
  - context:
      cluster: gokulexi.shop
      namespace: production
      user: user2
    name: user2-context
current-context: user2-context
kind: Config
users:
  - name: user2
    user:
      client-certificate: /root/user2.crt
      client-key: /root/user2.key

---

apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMrRENDQWVDZ0F3SUJBZ0lNR0RITjVQSGY3WVdKaUtmZU1BMEdDU3FHU0liM0RRRUJDd1VBTUJneEZqQVUKQmdOVkJBTVREV3QxWW1WeWJtVjBaWE10WTJFd0hoY05NalV3TXpJNU1EWXdNVFUwV2hjTk16VXdNekk1TURZdwpNVFUwV2pBWU1SWXdGQVlEVlFRREV3MXJkV0psY201bGRHVnpMV05oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGCkFBT0NBUThBTUlJQkNnS0NBUUVBMkg3a2N2VWFGQmV4Wkk1SGhIS0RMMHZVZkJUWlQxVFZRbll1ajZkcmp3d2QKT05qZHdwZ25mZlQ5L0IycmNDSDZ4VjN5azQ3am1LQVZhRkpMS081L2pVK2Y4R3hCS285d2NUSjF2Sk9hZDd0SAptUFBHU1R0UCtCa2xreG9iT3hHdmVVK1FBUGdlT0ZzM1lqa2NYNEdhOHZzUU15TEN0WGJhZ3QyV3RJdTdzVHpGCng2N3pqczZKdVFFQk9iZ3FEdHJTY29BTjIyS00ySVMxOUI3UGZOL0IrclVWT1RvUzl5L2pTaERLWDduWGZwTjEKb2pubXNNUTdrMzdyYjNlbzQ2Y2g5c0JGL2svUzFQMjJmc3c1VXVWWlJPM05rQTlWMkJUaXMwci8za3ZycFUxNAo2SkN1enBqK2lMNEg3cGZyQTczNmc4WHFaM21HK2ZpRmh4MTNRVE1aK3dJREFRQUJvMEl3UURBT0JnTlZIUThCCkFmOEVCQU1DQVFZd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVW1TN2JXeW4zR3lNcHoxclkKNWpTejkrOTVnT293RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUxZdnZCMGdqMWc2N2tYR0Y2MCtqTWZadytsTgpYMGUrN0h2MzZlUTZFLyttQnozTEZ6U0hwZDJBVXlrUUc1T0c2ZTBQcWQ4YTFhc3hmVHRmUDY1Q2ZMbGhHaTlTCnNTdGJPc1BWWDFKRnU2Q3NvUUJpRUFldnY4cjNhRkp2T2dJVXlKd1R4L2t4eUZNdkZkeHQrbzRLWkFZMWtHSGwKVFhURlRhY0Z5bzRDSnQ2L0N5ODNKZnVOQTdjVDhwdWRtblcwak0yeEd2RHZHcXN0ekFTdXc0Nzl5VDVzaGlHYQpTTFczdUJKWDBQL3lDTWttaTg5OWRsQkhxTTVqaWdXdlNvdlF1ZE0yenR5cENrcDZWUTYxNzhrd0xOeWQwSDF0CmRzVjFRZ3R5UFdJMDJKOXNrYjAwWFRFLzNYUkVPL1Z2RXk5ZlJEL3RHYlIrSjBTNXFtTUFUeTIzR1dZPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      server: https://api.gokulexi.shop
      tls-server-name: api.internal.gokulexi.shop
    name: gokulexi.shop
contexts:
  - context:
      cluster: gokulexi.shop
      namespace: staging
      user: user3
    name: user3-context
current-context: user3-context
kind: Config
users:
  - name: user3
    user:
      client-certificate: /root/user3.crt
      client-key: /root/user3.key

---
apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMrRENDQWVDZ0F3SUJBZ0lNR0RITjVQSGY3WVdKaUtmZU1BMEdDU3FHU0liM0RRRUJDd1VBTUJneEZqQVUKQmdOVkJBTVREV3QxWW1WeWJtVjBaWE10WTJFd0hoY05NalV3TXpJNU1EWXdNVFUwV2hjTk16VXdNekk1TURZdwpNVFUwV2pBWU1SWXdGQVlEVlFRREV3MXJkV0psY201bGRHVnpMV05oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGCkFBT0NBUThBTUlJQkNnS0NBUUVBMkg3a2N2VWFGQmV4Wkk1SGhIS0RMMHZVZkJUWlQxVFZRbll1ajZkcmp3d2QKT05qZHdwZ25mZlQ5L0IycmNDSDZ4VjN5azQ3am1LQVZhRkpMS081L2pVK2Y4R3hCS285d2NUSjF2Sk9hZDd0SAptUFBHU1R0UCtCa2xreG9iT3hHdmVVK1FBUGdlT0ZzM1lqa2NYNEdhOHZzUU15TEN0WGJhZ3QyV3RJdTdzVHpGCng2N3pqczZKdVFFQk9iZ3FEdHJTY29BTjIyS00ySVMxOUI3UGZOL0IrclVWT1RvUzl5L2pTaERLWDduWGZwTjEKb2pubXNNUTdrMzdyYjNlbzQ2Y2g5c0JGL2svUzFQMjJmc3c1VXVWWlJPM05rQTlWMkJUaXMwci8za3ZycFUxNAo2SkN1enBqK2lMNEg3cGZyQTczNmc4WHFaM21HK2ZpRmh4MTNRVE1aK3dJREFRQUJvMEl3UURBT0JnTlZIUThCCkFmOEVCQU1DQVFZd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVW1TN2JXeW4zR3lNcHoxclkKNWpTejkrOTVnT293RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUxZdnZCMGdqMWc2N2tYR0Y2MCtqTWZadytsTgpYMGUrN0h2MzZlUTZFLyttQnozTEZ6U0hwZDJBVXlrUUc1T0c2ZTBQcWQ4YTFhc3hmVHRmUDY1Q2ZMbGhHaTlTCnNTdGJPc1BWWDFKRnU2Q3NvUUJpRUFldnY4cjNhRkp2T2dJVXlKd1R4L2t4eUZNdkZkeHQrbzRLWkFZMWtHSGwKVFhURlRhY0Z5bzRDSnQ2L0N5ODNKZnVOQTdjVDhwdWRtblcwak0yeEd2RHZHcXN0ekFTdXc0Nzl5VDVzaGlHYQpTTFczdUJKWDBQL3lDTWttaTg5OWRsQkhxTTVqaWdXdlNvdlF1ZE0yenR5cENrcDZWUTYxNzhrd0xOeWQwSDF0CmRzVjFRZ3R5UFdJMDJKOXNrYjAwWFRFLzNYUkVPL1Z2RXk5ZlJEL3RHYlIrSjBTNXFtTUFUeTIzR1dZPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      server: https://api.gokulexi.shop
      tls-server-name: api.internal.gokulexi.shop
    name: gokulexi.shop
contexts:
  - context:
      cluster: gokulexi.shop
      user: rajat
    name: rajat-context
current-context: rajat-context
kind: Config
users:
  - name: rajat
    user:
      client-certificate: /root/rajat.crt
      client-key: /root/rajat.key      