kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: user1-RoleBinding
  namespace: development
subjects:
- kind: User
  name: user1
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: user1-role
  apiGroup: rbac.authorization.k8s.io 

---


kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: user3-RoleBinding
  namespace: staging
subjects:
- kind: User
  name: user3
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: user3-role
  apiGroup: rbac.authorization.k8s.io 
